### ISSUE TITLE
Need License Update

### ISSUE THREAD

**Issue by sitingren** [conda-forge/vertica-python-feedstock#37]
### Comment:

@conda-forge/core I took over this repo and published a release recently. Even though I updated the license of `recipe/meta.yaml` from MIT to Apache-2.0, I still see https://anaconda.org/conda-forge/vertica-python shows "License: MIT". Is it possible to change it?

**Comment by hmaarrfk** [comment]
I think this is unfortunately a known issue. I am not sure where the tracking issue is at this point. But it seems much of this metadata is not overwritten on package upload.

**Comment by hmaarrfk** [comment]
i think this may have been fixed. try making a new release to test. just increment the build number and rerender

**Comment by jakirkham** [comment]
Agree with Mark this should be fixed (may need new package builds)

There are many issues & PRs related to this

The best high level discussion is here: https://github.com/conda/infrastructure/discussions/649
